[profile.default]
src = 'contracts'
out = 'out'
test = 'test/foundry'
libs = ['node_modules', 'lib']
script = 'scripts/foundry'
cache_path = 'cache-forge'
gas_reports = ["*"]

# solc_version = '0.8.14'

ffi = true

optimizer = true
optimizer_runs = 100

[fuzz]
runs = 500

[invariant]
runs = 500

[rpc_endpoints]
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
mainnet = "${ETH_NODE_URI_MAINNET}"
polygon = "${ETH_NODE_URI_POLYGON}"
goerli = "${ETH_NODE_URI_GOERLI}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
avalanche = "${ETH_NODE_URI_AVALANCHE}"
base = "${ETH_NODE_URI_BASE}"
linea = "${ETH_NODE_URI_LINEA}"
celo = "${ETH_NODE_URI_CELO}"
gnosis = "${ETH_NODE_URI_GNOSIS}"

[etherscan]
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}" }
goerli = { key = "${GOERLI_ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
avalanche = { key = "${AVALANCHE_ETHERSCAN_API_KEY}" }
base = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
linea = { key = "${LINEA_ETHERSCAN_API_KEY}"}
celo = { key = "${CELO_ETHERSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
gnosis = { key = "${GNOSIS_ETHERSCAN_API_KEY}" , url = "https://api.gnosisscan.io/api"}
